# Generated by Django 5.1 on 2024-08-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0010_livros_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='sinopse',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
