# Generated by Django 5.1 on 2024-08-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_alter_livros_sinopse'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='img_capa',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
