# Generated by Django 5.1.1 on 2024-09-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0014_alter_categoria_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='img_capa',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
