# Generated by Django 5.1.1 on 2024-09-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0015_alter_livros_img_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='img_capa',
            field=models.ImageField(blank=True, max_length=30, null=True, upload_to=''),
        ),
    ]
