# Generated by Django 5.1.1 on 2024-09-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0016_alter_livros_img_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='img_capa',
        ),
    ]
