# Generated by Django 5.1.1 on 2024-09-28 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0018_categoria_usuario_leitor_livros_leitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='leitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.leitor'),
        ),
    ]
