# Generated by Django 5.1.1 on 2024-09-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0020_alter_categoria_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='leitor',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='usuario',
        ),
    ]
