# Generated by Django 5.1.1 on 2024-09-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0025_alter_leitor_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leitor',
            name='usuario',
        ),
    ]
