# Generated by Django 5.1.1 on 2024-09-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0026_remove_leitor_usuario'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitor',
            name='livro',
            field=models.ManyToManyField(blank=True, related_name='leitores', to='livro.livros'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='leitor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='livros_leitor', to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livros',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='livros_usuario', to='usuarios.usuario'),
        ),
    ]
