# Generated by Django 5.1.1 on 2024-09-28 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0027_leitor_livro_alter_livros_leitor_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='leitor',
        ),
        migrations.AlterField(
            model_name='leitor',
            name='livro',
            field=models.ManyToManyField(blank=True, to='livro.livros'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
    ]
