# Generated by Django 5.1.1 on 2024-09-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0028_remove_livros_leitor_alter_leitor_livro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='nome_emprestado',
        ),
        migrations.AddField(
            model_name='livros',
            name='leitor_emprestado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livro.leitor'),
        ),
    ]
